version: "3"
services:
    mongodb:
        image: tutum/mongodb
        ports:
            - "27017:27017"
        volumes:
            - mongo-volume:/data/db
    redis:
        image: redis:alpine
        ports:
            - "6319:6379"
        volumes:
            - mongo-volume:/data
        expose:
            - "6379"

volumes:
    mongo-volume:
    redis-data:
